language: generic
services:
    - docker

before_install:
    - docker build -t jpmc9005/angular-test -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true jpmc9005/angular-test npm test

after_success:
    - docker build -t jpmc9005/frontend ./frontend
    - docker build -t jpmc9005/backend ./backend

    # log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push the images to docker hub
    - docker push jpmc9005/frontend
    - docker push jpmc9005/backend

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-3 
    app: ChatApp_multi-docker
    env: ChatappMultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-709982155892
    bucket_path: chatapp-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY